In [1]:
# Notebook to study the gammas emmited from the 2nubb events
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

# Notebook to read in the nexus files and only save the useful stuff to slim the files down
import os
import sys
import tables as tb
import numpy  as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import re
from matplotlib.colors import LogNorm  # Import LogNorm for logarithmic color scale
from matplotlib.cm import get_cmap

In [27]:
mbb_hits  = pd.read_hdf("/Users/mistryk2/Packages/nexus/mbb_test.h5", "MC/hits")
LQ_hits  = pd.read_hdf("/Users/mistryk2/Packages/nexus/Leptoquark_test.h5", "MC/hits")

In [36]:


Nevents = 100


set_10_A = []
set_10_B = []
set_100_A = []
set_100_B = []
set_1000_A = []
set_1000_B = []

columns_to_keep = ["x","y","z","energy"]

for index, id in enumerate(mbb_hits.event_id.unique()):

    event_A = mbb_hits[mbb_hits.event_id == id]
    event_A = event_A[columns_to_keep]
    event_A["id"] = index

    event_B = LQ_hits[LQ_hits.event_id == id]
    event_B = event_B[columns_to_keep]
    event_B["id"] = index

    if (index < 10):
        set_10_A.append(event_A)
        set_10_B.append(event_B)

    if (index >=10 and index <110):
        set_100_A.append(event_A)
        set_100_B.append(event_B)

    if (index >=110 and index <1110):
        set_1000_A.append(event_A)
        set_1000_B.append(event_B)

    if (index >1110):
        break
    

set_10_A = pd.concat(set_10_A, ignore_index=True)
set_10_B = pd.concat(set_10_B, ignore_index=True)

set_100_A = pd.concat(set_100_A, ignore_index=True)
set_100_B = pd.concat(set_100_B, ignore_index=True)

set_1000_A = pd.concat(set_1000_A, ignore_index=True)
set_1000_B = pd.concat(set_1000_B, ignore_index=True)

def WriteFiles(df, filename):

    # Open the HDF5 file in write mode
    with pd.HDFStore(f"../files/{filename}.h5", mode='w', complevel=5, complib='zlib') as store:
        # Write each DataFrame to the file with a unique key
        store.put('MC/hits',df, format='table')

print("Writing Files...")
WriteFiles(set_10_A, "set_10_A")
WriteFiles(set_10_B, "set_10_B")

WriteFiles(set_100_A, "set_100_A")
WriteFiles(set_100_B, "set_100_B")

WriteFiles(set_1000_A, "set_1000_A")
WriteFiles(set_1000_B, "set_1000_B")

Writing Files...

In [46]:
test = pd.read_hdf("../files/Leptoquark.h5", "MC/hits")
print(len(test.id.unique()))
display(test)

10000

           id         x         y         z    energy
0           0  0.792970  0.478760 -0.378173  0.001699
1           0  1.615139  0.924712 -0.714001  0.000751
2           0  2.400125  1.418987 -1.070506  0.000951
3           0  3.237821  1.803669 -1.441826  0.003012
4           0  4.078986  2.170552 -1.823132  0.001291
...       ...       ...       ...       ...       ...
9379812  9999 -4.672607 -4.587981 -5.940982  0.003390
9379813  9999 -4.666734 -4.593591 -5.944713  0.001360
9379814  9999 -4.667037 -4.599049 -5.943257  0.001799
9379815  9999 -4.665890 -4.600294 -5.941936  0.001047
9379816  9999 -4.666090 -4.599921 -5.941356  0.000667

[9379817 rows x 5 columns]

In [44]:
mbb_hits  = pd.read_hdf("/Users/mistryk2/Packages/nexus/mbb.h5", "MC/hits")
LQ_hits  = pd.read_hdf("/Users/mistryk2/Packages/nexus/Leptoquark.h5", "MC/hits")

In [45]:
mbb_hits = mbb_hits[["event_id","x","y","z","energy"]]
LQ_hits = LQ_hits[["event_id","x","y","z","energy"]]

mbb_hits = mbb_hits.rename(columns={'event_id': 'id'})
LQ_hits = LQ_hits.rename(columns={'event_id': 'id'})

WriteFiles(mbb_hits, "mbb")
WriteFiles(LQ_hits, "Leptoquark")